### ISSUE TITLE
Find 3 Project Subject Ideas

### ISSUE THREAD

**Issue by menhel** [TechnionYP5779/team4#102]
For our next meeting, we need to come up with at least 3 novel project ideas - see related [wiki page](https://github.com/TechnionYP5779/team4/wiki/Project-Subject-Ideas).

Even better, if each one will propose his own idea for a project subject, by the template shown in the wiki.

**Comment by yuvalron** [comment]
First idea by A'meer A'mer: Apartment Finder
https://github.com/TechnionYP5779/team4/wiki/Idea-%231:-Apartment-Finder

**Comment by yuvalron** [comment]
Second idea: Testock
https://github.com/TechnionYP5779/team4/wiki/Idea-%232:-Testock

**Comment by ameeramer** [comment]
Third idea: SmartCity Traveler
[(https://github.com/TechnionYP5779/team4/wiki/Idea-%233:-SmartCity-Traveler)]
