### ISSUE TITLE
warnings and errors

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#103]
Description	Resource	Path	Location	Type
The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files	singleton.java	/fluent.ly.4/src/main/java/a	line 1	Java Problem
The project was not built since its build path is incomplete. Cannot find the class file for java.lang.Object. Fix the build path then try building this project	fluent.ly.4		Unknown	Java Problem
Tip: Remove redundant curly braces	Rectangle.java	/fluent.ly.4/src/main/java/il/org/spartan/utils	line 49	SyntacticBaggage
Tip: Abbreviate parameter obj to o in method equals	PairsList.java	/fluent.ly.4/src/main/java/il/org/spartan/utils	line 43	Abbreviation

**Comment by ameeramer** [comment]
fixed in e9a02deb5fb220323f893c6f197ff97b9dea0a89

**Comment by yossigil** [comment]
use a proper commit message

**Comment by yossigil** [comment]
and add tests for the fix

**Comment by yossigil** [comment]
please include a screen dump of clean compile

**Comment by ameeramer** [comment]
![image](https://user-images.githubusercontent.com/19497043/48461574-fdb32e80-e7dc-11e8-8dc5-1697948eb87e.png)

**Comment by ameeramer** [comment]
yes, this commit e9a02deb5fb220323f893c6f197ff97b9dea0a89 fixes the warning.
