### ISSUE TITLE
use boxing, and unboxing library instead of $.intValue()

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#104]

**Comment by yossigil** [comment]
![image](https://user-images.githubusercontent.com/12775400/48462918-e414e580-e7e2-11e8-8d2d-8177c7bef7aa.png)

**Comment by yossigil** [comment]
@ameeramer: please do not close issues next time without checking what you did

**Comment by ameeramer** [comment]
Line 99 in as.java was fixed, so are the others, see picture of commit changes. maybe you should pull?

![image](https://user-images.githubusercontent.com/19497043/48462998-2ccc9e80-e7e3-11e8-973b-7f81ae623d3a.png)

**Comment by ameeramer** [comment]
@yossigil should I close this?

**Comment by yossigil** [comment]
please include a screen dump that shows that searches for intValue in the project yields only calls from unbox.

after that, you can close this

**Comment by ameeramer** [comment]
![image](https://user-images.githubusercontent.com/19497043/48464269-afeff380-e7e7-11e8-9372-7ce4f55217e1.png)
