### ISSUE TITLE
Check again that you do not use junit Assert, but only class azzert

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team4#106]
_From @yossigil on November 14, 2018 9:14_

You can do this manually, or write a script. it is up to you. 

_Copied from original issue: TechnionYP5779/team6#79_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#76

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#61

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#79

**Comment by moshesab** [comment]
Done.
