### ISSUE TITLE
Document a push procedure in a wiki page

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team4#107]
_From @yossigil on November 14, 2018 9:11_

Should include formatting, cleanup, tests, spartanization etc.

_Copied from original issue: TechnionYP5779/team6#78_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#122

**Comment by menhel** [comment]
See new wiki page: [Push Procedure](https://github.com/TechnionYP5779/team4/wiki/Push-Procedure)

**Comment by yossigil** [comment]
add a directive to format the code

**Comment by menhel** [comment]
Done.
[See updated wiki page](https://github.com/TechnionYP5779/team4/wiki/Push-Procedure)
