### ISSUE TITLE
Consolidate classres Range and range

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team4#108]
_From @yossigil on November 14, 2018 9:9_

if you created class Range (capitalized).

The correct design should  have three (internal?) classes,
one for infinite range bounded above,
another for infinite bounded below
and a third for a finite range.

for example,
range.to(3).to(2) generates an error,
range.to(3).fron(2) creates a finite range,

the person responsible for this should not be the person who wrote class Range

_Copied from original issue: TechnionYP5779/team6#77_

**Comment by yossigil** [comment]
use lower case since this is fluent

**Comment by yossigil** [comment]
hint, you need three different classes, for the three kinds of ranges, each supporting different functions

**Comment by ron4548** [comment]
@yossigil I don't understand. You said consolidate. We had 2 classes named Range, we moved the functionality of one of them to the other. Where should three classes come from?

**Comment by 0xYuval** [comment]
Sprint-Zero is done.
