### ISSUE TITLE
Reopen all non-trivial issues, and make sure that someone else closes them

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team4#109]
_From @yossigil on November 14, 2018 9:2_

in particular, if you closed an non-trivial issue, reopen it, and ask someone else in your team verifies that the issue can be closed.

_Copied from original issue: TechnionYP5779/team6#76_

**Comment by yossigil** [comment]
Do not close this issue, without demonstrating that you indeed fixed some closed issues.

**Comment by yossigil** [comment]
all open/reclosed issues should include a reference to this issue...
