### ISSUE TITLE
refactor the code so that it uses box and unbox 

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team4#110]
_From @yossigil on November 14, 2018 9:17_

code should not include e.g., `x.intValue` or `Short.valueOf(3)`, except for in class box and class unbox

_Copied from original issue: TechnionYP5779/team6#81_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#125

**Comment by yossigil** [comment]
label? milestone?

**Comment by menhel** [comment]
last commit closed the issue, as there was no need to refactor src/test.
Done.
