### ISSUE TITLE
Test runs should be with assertions enabled

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team4#111]
_From @yossigil on November 14, 2018 9:21_

Play with eclipse, it is better to write
`assert x`
then
`azzert.isTrue(x)`

but when you run tests the jvm should have assertions enabled

_Copied from original issue: TechnionYP5779/team6#82_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#81

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#66

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#84

**Comment by yossigil** [comment]
You should use a jvm flag. Can you please show where this flag is set? use screen dump if necessary

**Comment by ameeramer** [comment]
@maxcalderon1997 @moshesab @menhel @Rany615 @ron4548 @yuvalron Please add a screen dump showing that you set the flag.

**Comment by menhel** [comment]
Done.
![image](https://user-images.githubusercontent.com/28152692/48631781-00be4280-e9c8-11e8-91f5-5c630e0b7519.png)

**Comment by ron4548** [comment]
![image](https://user-images.githubusercontent.com/4895877/48665310-c088be00-eab4-11e8-87b8-7cb7478ccb20.png)
Done.

**Comment by moshesab** [comment]
![image](https://user-images.githubusercontent.com/23172912/48666631-5846d600-eace-11e8-9451-3805d8cbb256.png)
Done.

**Comment by maxcalderon1997** [comment]
![image](https://user-images.githubusercontent.com/19844997/48781260-59e9e700-ece4-11e8-8bdd-71728bdc2863.png)
done.

**Comment by menhel** [comment]
@yuvalron Please provide a screen dump

**Comment by yuvalron** [comment]
![image](https://user-images.githubusercontent.com/19504086/48802579-4c4e5480-ed18-11e8-9112-ad1b8ea7e29a.png)

**Comment by Rany615** [comment]
![screenshot from 2018-11-20 13-32-50](https://user-images.githubusercontent.com/24301335/48804203-a9e4a000-ed1c-11e8-9b6c-d772f1d4af4d.png)
