### ISSUE TITLE
Integrate github issues with eclipse

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team4#112]
_From @yossigil on November 14, 2018 9:24_

for this, you need a proper mylyn connector. Best done by one team member figruing this out, and then
letting him instruct other members.

in short, github issues should be shown in the eclipse task list view.

![image](https://user-images.githubusercontent.com/12775400/48472870-e174b900-e7ff-11e8-8357-cf6c77bd12c5.png)

this is what the end results looks like in my machine. I can even see this issue on my eclipse:

![image](https://user-images.githubusercontent.com/12775400/48473379-03bb0680-e801-11e8-99b9-64c5d470c03a.png)

_Copied from original issue: TechnionYP5779/team6#83_

**Comment by dormaayan** [comment]
_From @yossigil on November 14, 2018 9:26_

be sure to enter the github password to and save it in eclipse, otherwise, you will get errors in synching.

here is where you add the password

![image](https://user-images.githubusercontent.com/12775400/48473150-8c857280-e800-11e8-8b18-152753de853c.png)

**Comment by dormaayan** [comment]
_From @yossigil on November 14, 2018 9:30_

![image](https://user-images.githubusercontent.com/12775400/48473035-3dd7d880-e800-11e8-8753-e906d36a448d.png)

this is where you add repos.

**Comment by dormaayan** [comment]
_From @yossigil on November 14, 2018 9:37_

hint, do an internet search

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#127

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#82

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#67

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#85

**Comment by yossigil** [comment]
milestone?

**Comment by ameeramer** [comment]
![image](https://user-images.githubusercontent.com/19497043/48616207-98f20280-e99b-11e8-8af2-2ffb316a9ef6.png)

**Comment by yuvalron** [comment]
![image](https://user-images.githubusercontent.com/19504086/48616440-4fee7e00-e99c-11e8-90ec-02c48fc86653.png)

**Comment by menhel** [comment]
Done.
![image](https://user-images.githubusercontent.com/28152692/48661766-23139700-ea80-11e8-8d1f-ce3b375f8e4c.png)

**Comment by ron4548** [comment]
![image](https://user-images.githubusercontent.com/4895877/48665260-05f8bb80-eab4-11e8-9b87-c0151d6b3139.png)
Had some problems, but now it is working.

**Comment by moshesab** [comment]
![image](https://user-images.githubusercontent.com/23172912/48666604-dbb3f780-eacd-11e8-8cea-6a9ffc8d280d.png)

**Comment by maxcalderon1997** [comment]
![image](https://user-images.githubusercontent.com/19844997/48782451-e72e3b00-ece6-11e8-974a-881f17eb58ff.png)
