### ISSUE TITLE
connect your project to SonarQube

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team4#113]
_From @yossigil on November 14, 2018 9:40_

for now, just connect. later we shall decide which rules to use.

_Copied from original issue: TechnionYP5779/team5#128_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#83

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#68

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#86

**Comment by menhel** [comment]
Integrated with our repository.

![image](https://user-images.githubusercontent.com/28152692/48476002-94e0ac00-e806-11e8-8821-4f381ba75de1.png)
