### ISSUE TITLE
  @SuppressWarnings("boxing")

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#114]
_From @yossigil on November 14, 2018 11:9_

This should never occur in the code, perhaps with the exception of class "box"
Use class box, and/or box.it() instead.

Only close this issue with a screen dump showing search for   @SuppressWarnings("boxing")

_Copied from original issue: TechnionYP5779/team6#87_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#129

**Comment by ameeramer** [comment]
![image](https://user-images.githubusercontent.com/19497043/48617230-87f6c080-e99e-11e8-9626-ee492490c94a.png)

**Comment by yossigil** [comment]
not done

**Comment by ameeramer** [comment]
ae5810c4fb6c8c396b790972668cbea131a57da3  this commit fixed it. it was committed after f32dbce

**Comment by menhel** [comment]
No boxing warnings are suppressed in the code. See seach result for `"boxing"` below:
![image](https://user-images.githubusercontent.com/28152692/48787027-acc99b80-ecf0-11e8-88d1-18cdcb22e2ec.png)
