### ISSUE TITLE
Create a cleanup profile for eclipse, and save it with your projecrt

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#116]
_From @yossigil on November 14, 2018 11:21_

Connect this profile with the wiki you created for a commit procedure

![image](https://user-images.githubusercontent.com/12775400/48479501-315b7c00-e810-11e8-997e-c2a63792c609.png)

_Copied from original issue: TechnionYP5779/team6#88_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#131

**Comment by yuvalron** [comment]
![image](https://user-images.githubusercontent.com/19504086/48616189-8677c900-e99b-11e8-840d-196dfc611e07.png)

**Comment by ron4548** [comment]
![image](https://user-images.githubusercontent.com/4895877/48659227-8c7eb000-ea56-11e8-95fa-cba42a0da689.png)

**Comment by menhel** [comment]
![image](https://user-images.githubusercontent.com/28152692/48661877-cadd9480-ea81-11e8-9b30-d5a11205ce02.png)

**Comment by moshesab** [comment]
![image](https://user-images.githubusercontent.com/23172912/48665769-1eb99f00-eabd-11e8-86e2-c8ec1e558f29.png)

**Comment by yossigil** [comment]
just export the configuration, and commit the xml

**Comment by maxcalderon1997** [comment]
![image](https://user-images.githubusercontent.com/19844997/48783079-3fb20800-ece8-11e8-9c74-aefedd94dde1.png)

**Comment by Rany615** [comment]
![screenshot from 2018-11-20 13-28-51](https://user-images.githubusercontent.com/24301335/48804084-5a05d900-ed1c-11e8-9fc8-885892ad2936.png)
