### ISSUE TITLE
move separate.TEST to the test hierarchy

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#122]

**Comment by ron4548** [comment]
@yossigil same as #120, the tests contain access to internal methods of internal class. What do you want me to do? delete the specific test or change the visibility of the method?
![image](https://user-images.githubusercontent.com/4895877/48621874-a44e2980-e9ad-11e8-8458-e9d78e87c585.png)
"The method separateBy(Object[], String) from the type separate.SeparationSubject is not visible"

**Comment by ron4548** [comment]
Done. Changed the method access modifier from 'private' to 'package private' (default)
