### ISSUE TITLE
add some more descriptive stuff in your readme.md file

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#123]
_From @yossigil on November 8, 2018 17:37_

remember this is how people will see you project on the web

_Copied from original issue: TechnionYP5779/team6#64_

**Comment by menhel** [comment]
Done. See new readme file in the [code section](https://github.com/TechnionYP5779/team4).

**Comment by yossigil** [comment]
but this is not the spartanizer project....

**Comment by menhel** [comment]
Updated to suit the project description. Done.

**Comment by yossigil** [comment]
commit#?

**Comment by yossigil** [comment]
and this is not the spartanizer; just a small library...

**Comment by menhel** [comment]
Done. Commit dd75968cfa7498e7ead2fc083e87dc12a2b2f8cd

**Comment by jtarver2018** [comment]
Commit
