### ISSUE TITLE
Yuval's Personal Progress

### ISSUE THREAD

**Issue by yuvalron** [TechnionYP5779/team4#128]
**Project Ideas:**
#102 Find 3 Project Subject Ideas
- [Testock](https://github.com/TechnionYP5779/team4/wiki/Idea-%232:-Testock) 

**Unit Tests:**
#27 Unit tests for class Bool
#30 Unit tests for class Int
#35 Unit tests for class Truth
#43 Unit tests for interface nil

**Improving coverage (#52):**
Created the following Unit tests: 
NoteTest (8dc6a9b126e17c9658a04b1337dc8988386e105a)
StrTest (97ba046caa58ee7ee0e4c25bceade54a49e742cf)
BinaryTest (0cef37ad3ecbb2686f069f692dc5e282c0aef664)
RangeTest (d4ba4b83391e312b016b1712ae680cbbf15d87b6, fd4587e8fc8a09f2a217b0236c8ae1325f940f79)
LongestCommonSubsequnceTest (17dfb472d456eb51c586a4f3869dd48e3be4030a)
ChainStringToIntegerMapTest (45b9313ee7ec0bd6e6b26985f46a23e235b2f34a)
AccumulatorSquarerTest (8f779f1507d2e70e13b20f4f4b381eb926b21946)
AccumulatorSummerTest (ce118f01574cea2a2b2f3cb22810df292ae9d3cf)
ReduceTest & ReduceStringConcatenateTest (1a6291a0d8c88706bf9c0ff849236d678a396dde)
CountingReduceTest (0f7065aba9fbb6d8ad2591c20d67d25050de09d2)
FirstNotNullReduceTest (5506db5901b04f534e1020950083f135e4764a13)
BooleanOrReducerTest (9ade7126aaf93bd03d3ca2db49b40a72260422a9)
PropositionTest (abbd62f3bfc1942a89e3b9248da3a4c5a87377d8)
PropositionPrettyPrinterTest (8ce13c38e38e075fc62120d51478cd25a9b86cd9)
ImutibaleStatisticsTest (33cd1f6cd5ec646402448b757320520554eec669)
YesTest (76e2bc4e07e71a0f30c11d16f4e69149869f2e9f)
ZeroTest (c9ee6c2fc0c52c7ff65edf49c45f78a9c59de1d5)
NotTest (5545765afa904df52db3f0c7a05752ae589df884)
DeTest (c9d03838ebbd186f7290b2450f0ceb2c0180c904)
OnceTest (629dd38ba520983a06f0b671a79a0f5bb57f8959)
...And improved many others.

**Team reporisory maintenance:**
#87 Mark all duplicate issues with the label duplicate: #79 #80 #81 #82
#90 Make sure all closed issues have an assignee
#93 make sure all issues, including closed ones, have a milestone
#95 Please use commits not pull requests
#101 Commit Checklist
#121 Change milestone "Sprint 0" to "Sprint-Zero"
Added [Sidebar](https://github.com/TechnionYP5779/team4/wiki) to our Wiki

**Other:**
#55 move function read() from class FileUtils to class file
#74 use tdd to develop a fluent api that represents an arithemtical progression over BigInteger
#144 make sure zero class and other fluent classes like this e.g., de.fault, are in fluent.ly

**Set-up environment:**
#3 foo
#5 Karma and Todos for Yuval Ron
#12 Make sure all team members have a setup gitprofile.
#14 setting up the working environment of Yuval Ron and Guy Menhel
#67 Set up running environment - Yuval Ron
#111 Test runs should be with assertions enabled
#112 Integrate github issues with eclipse
#116 Create a cleanup profile for eclipse, and save it with your projecrt

**Comment by yossigil** [comment]
please specify which TDD you did, which class you documented, and which were the 3-5 most heavy issues you did

**Comment by yuvalron** [comment]
Most heavies issues I did:
- #52 Improving source coverage
- #102 Thinking about project ideas and documenting the "Testock" idea
- #74 Implementing BigInteger TDD

**Comment by 0xYuval** [comment]
Sprint-Zero is done.
