### ISSUE TITLE
polish your code: change box.box(x) to box.it(x), or to box(x); same with unbox

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#131]

**Comment by moshesab** [comment]
@yossigil 
It is bot.it():
![image](https://user-images.githubusercontent.com/23172912/48728392-8696f380-ec3d-11e8-9f7b-50783f9877a5.png)

or I didn't get what you mean

**Comment by yossigil** [comment]
why boxInteger when the name was box? please fix this

**Comment by menhel** [comment]
Duplicate for #138 and #146 which are now closed. 
Closed.
