### ISSUE TITLE
Moshe's Personal Progress

### ISSUE THREAD

**Issue by moshesab** [TechnionYP5779/team4#132]
Set-up environment:
#10 foo
#18  Karma and Todos for Moshe Sebag
#12 Make sure all team members have a setup gitprofile.
#50  setting up the working environment of Moshe Sebag
#70  Set up running environment - Moshe Sebag
#111 Test runs should be with assertions enabled
#112 Integrate github issues with eclipse
#116 Create a cleanup profile for eclipse, and save it with your projecrt

Team reporisory maintenance:
#95 Please use commits not pull requests
#101 Commit Checklist

Code refactoring:
#60 rm function hash() from class Pair, and use function hash() on Utils
#72 Refactor use of assertions
#106 Check again that you do not use junit Assert, but only class azzert
#119 Convert azzert.that(X, is(true)) to assert x  

Unit Tests:
#40 Unit tests for interface as

#52 Increase code coverage to 60%; for this you need to run "coverage as":
made unit tests for all etc package and more.

**Comment by yossigil** [comment]
please specify which TDD you did, which class you documented, and which were the 3-5 most heavy issues you did

**Comment by 0xYuval** [comment]
Sprint-Zero is done.
