### ISSUE TITLE
make sure all team members have a personal progress issue

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#134]

**Comment by menhel** [comment]
@Rany615 @maxcalderon1997 
Please add a personal progress page. You can look at ours in the issue tab.

**Comment by ameeramer** [comment]
@Rany615 ...

**Comment by menhel** [comment]
Closed. 
#128 Yuval's Personal Progress
#132 Moshe's Personal Progress
#141 Ron's Personal Progress
#145 Guy's Personal Progress
#147 Ameer's Personal Progress
#149 Max's Personal Progress
#151 Rany's Personal Progress
