### ISSUE TITLE
Ron's personal progress

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/team4#141]
### Intro and Setup
#2 Foo
#11 Karma and Todos for Ron Marcovich
#12 Make sure all team members have a setup gitprofile
#111 Test runs should be with assertions enabled
#112 Integrate github issues with eclipse
#116 Create a cleanup profile for eclipse, and save it with your project

### Most heavy issues I resolved
#20 Make sure all tests conform to the recommended maven structure
#88 move all inner TEST classes to the test hierarchy
#117 eliminate all @SuppressWarnings

### Unit tests
#28 Unit tests for class box
#31 Unit tests for class Pair
#36 Unit tests for class unbox
#37 Unit tests for enum empty

For #52 wrote tests for:
- class All
- class FilesGenerator

### TDD
#89 Use TDD to develop a function iterables.alternate that takes two iterables, and returns an iterable that returns elements in these in alternating order, until the shortest

### Maintainance missions
#120 move prune.TEST1/2 to the test hierarchy
#122 move separate.TEST to the test hierarchy
#133 For each class X, test class should be named XTest, not X_Test, neither XTests, nor xTests, etc. this includes case matching, and also folder matching

### Contributed also to:
#52 Increase code coverage to 60%; for this you need to run "coverage as"
Wiki page for Idea 2: Testock

**Comment by 0xYuval** [comment]
Sprint-Zero is done.
