### ISSUE TITLE
Guy's Personal Progress

### ISSUE THREAD

**Issue by menhel** [TechnionYP5779/team4#145]
### Heaviest Issues I Dealt With
#63 make sure there are no warnings on code
#110  refactor the code so that it uses box and unbox
Extensive research for the SmartCity Traveler idea and writing of the [Wiki Page](https://github.com/TechnionYP5779/team4/wiki/Idea-%233:-SmartCity-Traveler)

### Introduction & Set Up
#1 Foo
#4 Prepare a team wiki with a schedule for the semester, including all constraints.
#12 Make sure all team members have a setup gitprofile
#13 Introduction Page
#14 Setting up a working environment
#111 Test runs should be with assertions enabled
#112 Integrate github issues with eclipse
#116 Create a cleanup profile for eclipse, and save it with your project

### Issues Resolved
#21 Setup Continuous Integration
#23 Kill dead packages: il.org.spartan.collections, il.org.spartan.bench, il.org.spartan.java
#53 Move all non-general-purpose code to il.org.spartan.etc
#54 move enum file from il.org.spartan.utils to fluent.ly
#56 change type of enum file to class file
#61 move function penultimate from Utils to interface list
#62 make sure all code is spartanized
#63 make sure there are no warnings on code
#98 eliminate @SuppressWarnings("boxing") placed for laziness
#99 clear run of tests
#107 Document a push procedure in a wiki page
#110  refactor the code so that it uses box and unbox
#113 connect your project to SonarQube
#123 add some more descriptive stuff in your readme.md file
#129  include a link to sonarqube and lgtm in your readme.md
#138 unbox.unboxInteger should be unbox.unbox; same for other types
#139 Polish your code: Utils.cantBeNull(x) -> cantBeNull(x)
#140 REMOVE ASSERTfALSE FROM CLASS SEAPRATEtEST; THEY DO NOT BELONG THERE
#142 no static void assertFalse(final @NotNull String reason, final boolean b) in separate
#143 Integrate Codecov Badge into ReadMe.md
#146 box.boxInteger should be box.it; same for other types
#148 Add code-style badge to readme.md

### Unit Tests
#34 Unit tests for class Statistics
#42 Unit tests for interface is
#44 Unit tests for interface singleton
#46 document interface forget and add unit tests
#52 Increase code coverage to 60%; for this you need to run "coverage as

### TDD
#91 use TDD to define class angle

### Project Ideas
#102 Find 1/3 Project Subject Ideas (SmartCity)
#102 Developed 2/3 ideas (SmartCity & Testock)

**Comment by 0xYuval** [comment]
Sprint-Zero is done.
