### ISSUE TITLE
Ameer's Personal Progress

### ISSUE THREAD

**Issue by ameeramer** [TechnionYP5779/team4#147]
### Introduction and Set Up:
#7 foo
#12 Make sure all team members have a setup gitprofile.
#19 Karma and Todos for A'meer A'mer
#49 setting up the working environment of A'meer A'mer
#65 make sure the code runs

### Unit Tests
#29 Unit tests for class idiomatic
#32 Unit tests for class Range
#34 Unit tests for class Statistics
#38 Unit tests for interface anonymous
#40 Unit tests for interface as

### Other issues
#48 consolidate class Wrapper into Outer
#58 rename function readFromFile to read
#63 make sure there are no warnings on code
#103 warnings and errors
#104 use boxing, and unboxing library instead of $.intValue()
#105 consolidate function unused into interface forget
#111 Test runs should be with assertions enabled
#112 Integrate github issues with eclipse
#114 @SuppressWarnings("boxing")
#116 Create a cleanup profile for eclipse, and save it with your projecrt
#124 Eliminate LGTM alerts
#115 @SuppressWarning of "static-method"
#150 Eliminate as much as possible SonarQube bugs.

### Commits done to increase coverage #52 
89bd63a0b7f583b953029ba4ea0442d76de82c0a #52: moved utils test outside of class, which raised it's coverage
7d0b6d2e917e8f4baa57eb8aace45be3b379b83c #52: raised the coverage to 50 percent
d9cec157c3cf6f0543e3d7bd60e9877ad775870f #52: added test for Utils to increase the coverage
d902ff17d1d83303cd6e7319c80e07270afe23ad #52: deleted test that printed to console
2a9acaa07e81bcdcd43a437db9bcbb330a4b347e #52: added tests to class the to increase coverage
278a290a8609afceafa010c4d8d35bb3d5cacde4 #52: added more tests to class the
057c43f85958bfb811d2e2e0b8824922e2b9bd1c #52: increased coverage by adding tests to class has
82f0a091e2bd23f31d7f19fd48cfb83669ff11e1 #52: added more test to class the
8c8ed9972c485281d424feba1e79aa16169c7efc #52: added tests for CSV class
b0c699e7fcdf6e442925770138d69f7df2ef2fa2 #52: refactored CSV tests to handle different newline styles at diffe…
10526ddb71271f7cfb4d74d180cb2fd30f04acc8 #52: added tests for Separator class
ca4820d0256f0bc0e3c907cb510510e57e50c1f8 #52: added tests for CSVLine class
8db9f4dce849d6eba48be860516528a825dbffc5 #52: added test for class note
2056d62c2bdbe79960b15787d9e1bdc2d053e045 #52: added test for class dump
0d71906939de641a2514a4ed3c5875e9dbd21f6f #52: enhanced test for class dump
17c4ef00c38f93b50701cbcdf906203080ab8e5b #52: added tests for class Rule
f562a4437bf27e7a555a1876e0a1fe38c5324cb1 fixed #52: added tests for PropositionReducer
52a288393f81d9f21de9aa1dc710a784f1f84232 added TableTest, coverage at 61.8

### Other important contributions
* Connected the project with LGTM
* 4543281d045f884e791145061e1764d7bfe12f02 refactored some tests to have only one assert in each test
* Made sure functional Programming is used where possible: i.e. commit fa915751c0f5e07c6b03bd094e0d4251e175d471
* Added the Wiki page to set up environment [Get Started](https://github.com/TechnionYP5779/team4/wiki/Getting-Started)
* Added the wiki page to help integrate GitHub issues in Eclipse [Integrating GitHub Issues](https://github.com/TechnionYP5779/team4/wiki/Integrating-GitHub-Issues-With-Eclipse)

### TDD
#76 use tdd to define a class that defines a list of pairs of real numbers

### Heaviest Issues Dealt With
#52 Increase code coverage to 60%; for this you need to run "coverage as"
#124 Eliminate LGTM alerts
#76 use tdd to define a class that defines a list of pairs of real numbers

### Project Ideas
#102 Find 3 Project Subject Ideas
* [Apartment Finder](https://github.com/TechnionYP5779/team4/wiki/Idea-%231:-Apartment-Finder)

**Comment by 0xYuval** [comment]
Sprint-Zero is done.
