### ISSUE TITLE
Max's Personal Progress

### ISSUE THREAD

**Issue by maxcalderon1997** [TechnionYP5779/team4#149]
**Introduction and Set Up:**
#9 foo
#12 Make sure all team members have a setup gitprofile.
#17 Karma and Todos for Max Calderon
#51 setting up the working environment of Max Calderon and Ron Marcovich
#69 Set up running enviroment - Max Calderon

**Team reporisory maintenance:**
#95 Please use commits not pull requests
#101 Commit Checklist
#111 Test runs should be with assertions enabled
#112 Integrate github issues with eclipse
#116 Create a cleanup profile for eclipse, and save it with your projecrt

**Code refactoring:**
#72 Refactor use of assertions

**TDD**
#75 Use tdd to develop representing recangles in the plane defined by two corner points

**Heaviest Issues Dealt With**
#52 Increase code coverage to 60%; for this you need to run "coverage as"
#75 Use tdd to develop representing recangles in the plane defined by two corner points

**Comment by 0xYuval** [comment]
Sprint-Zero is done.
