### ISSUE TITLE
Rani's personal progress

### ISSUE THREAD

**Issue by Rany615** [TechnionYP5779/team4#151]
Introduction and Set Up:
#8  foo
#12 Make sure all team members have a setup gitprofile.
#25 Karma and Todos for Rani Jammal
#26 setting up the working environment of Rani Jammal
#68 make sure the code runs

Team:
#116 Create a cleanup profile for eclipse, and save it with your projecrt
#95 Please use commits not pull requests
#101 Commit Checklist
#111 Test runs should be with assertions enabled

#59 move function in() from interface Utils to interface is, erasing duplicates

TDD
#73 Define class range using tdd

**Comment by yossigil** [comment]
the links are still broken. Fix them! they are to the new project. They should be to the old.

**Comment by Rany615** [comment]
im closing this because its on this team, theres another one on the new team, TechnionYP5779/team3#146
