### ISSUE TITLE
eliminate tokenizer.flex

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#153]

**Comment by ron4548** [comment]
Identifier "tokenizer" doesn't exist in our project. Same for "flex".
![image](https://user-images.githubusercontent.com/4895877/48824363-bb559880-ed6c-11e8-9478-bddad69afecc.png)
![image](https://user-images.githubusercontent.com/4895877/48824382-cf00ff00-ed6c-11e8-8205-26b44315cf95.png)
