### ISSUE TITLE
Analyzing Safot website

### ISSUE THREAD

**Issue by menhel** [TechnionYP5779/team4#156]
We need to analyze [safot website](https://safot.cs.technion.ac.il/user/%D7%99%D7%95%D6%B9%D7%A1%D6%B4%D7%99+%D7%92%D6%BC%D6%BC%D6%B4%D7%99%D7%9C/activity):
- How can we improve this website?
- How can we integrate our features of "Testock" into it?
- How can we integrate our idea of chrome plugin?
- Understand which technologies were used to create this website

**Comment by maxcalderon1997** [comment]
[features of safot website.docx](https://github.com/TechnionYP5779/team4/files/2619097/features.of.safot.website.docx)
i listed some features in Safot website. This list in not complete because I wasn't sure about some of it's features. You're all welcome to comment on the list and fix it.

**Comment by yuvalron** [comment]
A nice feature is the ability to rate users based on their activity.
