### ISSUE TITLE
define ParkingLot class using TDD

### ISSUE THREAD

**Issue by moshesab** [TechnionYP5779/team4#158]
As part of our parking system we should define a class that will represent a parking lot space.

The class will enable the following:

- [x] getID() - returns the parking lot unique ID number.

- [x] getLocation() - returns a Pair of coordinates of the parking lot location.

- [x] getOwner() - returns a User object that represent the owner of the parking lot.

- [x] getPricesArray - return an array list of Intgers where the number in the i'th place represent the price for a hour of parking in the i'th day ( 0 for Sunday, 1 for Monday and so on).

- [ ] getPriceForDay(String day) - returns the price for an hour of parking in a given day.

- [ ] IsAvailbe(Date start, Date end)- returns true <=> the parking lot available in the given range of time.

- [ ] setAvailble(Date start, Date end) - set the given times to be available in the parking lot.

- [ ] setOccupied(Date start, Date end) - set the given times to be not available in the parking lot.

- [ ] setPrices - set new prices for each of the days.

- [ ] setPrice - set a new price for a given day.

**Comment by 0xYuval** [comment]
#166 ParkNet project was moved to a new repository.
