### ISSUE TITLE
Design a database schema that describes the project structure

### ISSUE THREAD

**Issue by ameeramer** [TechnionYP5779/team4#159]

**Comment by ameeramer** [comment]
@moshesab @ron4548 this is a basic possible schema, would like to discuss it with you.

![image](https://user-images.githubusercontent.com/19497043/49078408-9b2f4900-f246-11e8-9aff-8a45944f128c.png)

**Comment by 0xYuval** [comment]
#166 ParkNet project was moved to a new repository.
