### ISSUE TITLE
Testock Presentation

### ISSUE THREAD

**Issue by yuvalron** [TechnionYP5779/team4#161]
@menhel, can you please upload the "Testock" presentation we created for the meeting tomorrow?

**Comment by menhel** [comment]
Sure. Here you go.
https://technionmail-my.sharepoint.com/:p:/g/personal/menhel_campus_technion_ac_il/EcQazhvNG8VLn9jgy4nRxIMBNDuCZsS0LZfkcJKr_6oxNw?e=xPHwDL
