### ISSUE TITLE
Search for a gui tool

### ISSUE THREAD

**Issue by moshesab** [TechnionYP5779/team4#163]

**Comment by ron4548** [comment]
We will build it as Android application and therefore will use Android SDK and optionally other SDKs for more complicated UI components

**Comment by yossigil** [comment]
not a good idea, because you would have problems in delivering the first iteration

**Comment by ron4548** [comment]
> not a good idea, because you would have problems in delivering the first iteration

What do you mean? We already have a working app with basic functionality as you can see in the other repository: https://github.com/TechnionYP5779/Parknet

**Comment by yossigil** [comment]
Ok. will sort it out later. thanks

**Comment by 0xYuval** [comment]
#166 ParkNet project was moved to a new repository.
