### ISSUE TITLE
Safot: get DB from the website's admins

### ISSUE THREAD

**Issue by menhel** [TechnionYP5779/team4#170]
Try to contact Daniel Mittleman or any other admin of safot website to get it's DB.
If stuck, try to contact Yossi, he can help.

**Comment by 0xYuval** [comment]
It turns out that Daniel Mittleman and Daniel Mitleman (one "t") are different persons... :) 

Sent Daniel Mittleman (hopefully, the right person) a message on Facebook...

**Comment by 0xYuval** [comment]
I also asked for a relevant contact on the Faculty Facebook group

**Comment by 0xYuval** [comment]
@maxcalderon1997 Please ask Itay Dabran if has some information about it
