### ISSUE TITLE
Accenture Project Idea

### ISSUE THREAD

**Issue by 0xYuval** [TechnionYP5779/team4#174]
**Title: Agile Security – Cyber Security Remediation Service**

**Abstract:**

Accenture’s Cyber Fusion Center in Herzelia offers a final year project to Technion students that would be part of cutting edge technology delivered to Accenture’s clients termed Agile Security. In parallel to the project, participating students can apply for a student internship position at Accenture R&D Labs.

As part of Agile Security project, the students scope will be to construct a micro-service of Cyber Security Remediation, learn underlying technologies and understand cyber security processes.

The technology will utilize Virtualization (VMWare) and Containers (Docker) environments, employ cloud collaboration tools and Agile (SCRUM) project management techniques.

The students will be responsible for the entire eco-system of their service including the delivery of the macro-services code base (Python or Java), Docker manifest, test driven server, service and code documentation, and packing and deployment DevOps scripts.

Accenture Technology team leads will assist in requirements understanding, meet with the students and their mentor to better align the needs in order to ensure quality levels.

For those accepted for internship, an opportunity exists for continuation towards full time employment in Accenture R&D Labs at Herzelia.

**About Accenture:**
Accenture is a 460,000 employees company, with the largest cyber security organization in the globe.
Accenture Labs are the innovation and research organization of Accenture.
The Herzelia Lab is part of 7 Labs globally, focusing on AI, Cyber Security and Industry 4.0.

**Comment by 0xYuval** [comment]
More details: https://bit.ly/2JeXhgL
Presentation from Cyber week

**Comment by 0xYuval** [comment]
[technion students.docx](https://github.com/TechnionYP5779/team4/files/2664320/technion.students.docx)

Accenture’s Agile Security methodology and technologies industrialize holistic cyber and business alignment by employing proactive automated cyber risk management. Agile Security solves the most problematic challenge of cyber security today - lack of resources against overwhelming defense missions. Agile Security improves business decision-making by helping business and security owners to prioritize security actions that are most critical to their business. In essence, Agile Security assists owners to be informed on what is the next remediation action to be acted upon now, and why.
By simulating virtual adversary attacks and analyzing impact on business processes and their underlying assets, Agile Security analytics engines recommend surgical prioritized actions for gradually reducing business risks and inform external service desk and SOC on a needed workplan. Once the workplan is completed, Agile Security verifies the change on the virtual adversary attack potential and accordingly reduces the risk estimation.

As depicted in the Figures, for reduction of business risks, Agile Security automation continuously interlaces three aspects:
•	Vulnerability of assets or Configuration Items (CI) - the cyber intelligence and discovery aspects of the Information Technology (IT) and Operations Technology (OT) elements.
•	Value of the assets - the value of the business processes and organizational aspect of a Profit and Loss (P&L) or other segmented section and area in the organization. 
•	Probability or Likelihood of targeted assets to be breached - the hacking and risk analytics of the IT and OT systems, performed in a non-intrusive manner.
As a result, Agile Security assists in integrating cybersecurity with business risk management, focusing on:
•	Increasing business operational efficiency and availability.
•	Maximizing existing, and reducing additional, cyber investments.
•	Growing organization cyber resilience.

**Comment by 0xYuval** [comment]
![1](https://user-images.githubusercontent.com/19504086/49752079-ee2de500-fcb7-11e8-84bd-4ce36e0630ed.jpg)

**Comment by 0xYuval** [comment]
![2](https://user-images.githubusercontent.com/19504086/49752134-20d7dd80-fcb8-11e8-8f49-904b281fd333.jpg)

**Comment by menhel** [comment]
@yuvalron and me talked with Avi Dayan, head of R&D at Accenture and have a pretty good idea about the project's details.
Need to schedule a conference call between all group members and decide how to proceed. Started a conversation via Telegram.
