### ISSUE TITLE
Unit tests for class Bool

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#27]

**Comment by dormaayan** [comment]
Please assign a team member to this issue ASAP

**Comment by yuvalron** [comment]
2hr

**Comment by yuvalron** [comment]
Worked on this for 0.5hr

**Comment by yossigil** [comment]
please provide a link to the commit that closed this issue

**Comment by yuvalron** [comment]
83772f71772e9c735b0455d855d7330cf78e4ef6
