### ISSUE TITLE
Unit tests for interface as

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#40]

**Comment by menhel** [comment]
Estimated work time: 3 hours

**Comment by yossigil** [comment]
WHEN SHALL WE SEE PROGRESS

**Comment by moshesab** [comment]
@yossigil hi, I WAS CHANGING NOW 
assertEquals(X, Y); to azzert.that(Y, is(X)); for about 3 hours now, so I had no time for this today.
HOPE TO FIND SOME TIME SOON. GN.

**Comment by ameeramer** [comment]
took 1.5 hours.
