### ISSUE TITLE
setting up the working environment of A'meer A'mer and Moshe Sabag

### ISSUE THREAD

**Issue by ameeramer** [TechnionYP5779/team4#49]

**Comment by yossigil** [comment]
This is not right. There should be a separate issue for each one of you.

**Comment by ameeramer** [comment]
The working environment for this project includes
- [ ] Linux
- [ ] Eclipe Neon
- [ ] Java 8 Programming
- [ ] Formatting conventions
- [ ] Spartan programming
- [ ] Fixed cleanup routine
- [ ] Highest level of warning settting
- [ ]  Git command line
- [ ] Telegram (might be changed by another messaging application)

**Comment by dormaayan** [comment]
@ameeramer , @moshesab : Please seperate this into two different issues and close this issue.
You should have the working environment all set for tommorow
