### ISSUE TITLE
setting up the working environment of Moshe Sebag

### ISSUE THREAD

**Issue by moshesab** [TechnionYP5779/team4#50]

**Comment by moshesab** [comment]
The working environment for this project includes
- [ ] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [x] Formatting conventions
- [ ] Spartan programming
- [ ] Fixed cleanup routine
- [ ] Highest level of warning settting
- [ ]  Git command line
- [ ] Telegram (might be changed by another messaging application)

**Comment by yossigil** [comment]
please include a screen dump of running maven tests from the command line

**Comment by moshesab** [comment]
@yossigil I did already [here](https://github.com/TechnionYP5779/team4/issues/70). Let me know if this is not enough. Thanks.

**Comment by yossigil** [comment]
IF YOU HAVE FOLLOWED THE ASSIGNMENT ALL THE WAY TO THE END, YOU SHOULD HAVE A HAD A KARMA PAGE...

**Comment by moshesab** [comment]
@yossigil I actually have one [here](https://github.com/TechnionYP5779/team4/issues/18). LET ME KNOW IF THIS IS NOT WHAT YOU WANTED. Thanks.

**Comment by yossigil** [comment]
thanks

, please try to provide complete answers next time.
also, include references to issues using #18 and #70
