### ISSUE TITLE
setting up the working environment of Max Calderon and Ron Marcovich

### ISSUE THREAD

**Issue by maxcalderon1997** [TechnionYP5779/team4#51]
The working environment for this project includes
- [ ] Linux
- [x] Eclipe Neon
- [x] Java 8 Programming
- [ ] Formatting conventions
- [ ] Spartan programming
- [ ] Fixed cleanup routine
- [ ] Highest level of warning settting
- [ ]  Git command line
- [x] Telegram (might be changed by another messaging application)

**Comment by yossigil** [comment]
You do not work in pairs. Please create a separate issue for each one of you.

**Comment by dormaayan** [comment]
@maxcalderon1997 , @ron4548 : Please create your own issues, assign yourself and close this one.
We expect you to have the environment all set for the meeting tommorow morning
