### ISSUE TITLE
Increase code coverage to 60%; for this you need to run "coverage as"

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#52]

**Comment by dormaayan** [comment]
Please assign all the team members to this issue, and refrence all the other relevant issues here

**Comment by menhel** [comment]
Estimated: 3 hours

**Comment by yossigil** [comment]
LET'S TRY AND SEE.

**Comment by ron4548** [comment]
Current coverage is 30.8%
![image](https://user-images.githubusercontent.com/4895877/48258758-997c1d80-e41e-11e8-99c1-e9e01735e48c.png)
The following issues should increase code coverage upon completion: #29 #32 #34 #40 #41 #42 #44 #46

**Comment by menhel** [comment]
Current coverage: 48.1%
![image](https://user-images.githubusercontent.com/28152692/48299616-2d5df000-e4d8-11e8-8f3a-f01f5137418f.png)

**Comment by ameeramer** [comment]
Current Coverage: 54.0%

![image](https://user-images.githubusercontent.com/19497043/48300941-80db3880-e4ee-11e8-8e07-26c98db37e51.png)

**Comment by yuvalron** [comment]
![image](https://user-images.githubusercontent.com/19504086/48301946-277b0580-e4fe-11e8-9c5f-f3e48c01c8ba.png)

Current coverage 57.9%

**Comment by dormaayan** [comment]
Keep going!

**Comment by ameeramer** [comment]
![image](https://user-images.githubusercontent.com/19497043/48302915-e4279380-e50b-11e8-8350-0a660095bfca.png)

**Comment by ameeramer** [comment]
took 4 hrs.

**Comment by yuvalron** [comment]
![image](https://user-images.githubusercontent.com/19504086/48614782-c177fd80-e997-11e8-97ec-a89d04e6b30f.png)
current is 42%

**Comment by yuvalron** [comment]
![image](https://user-images.githubusercontent.com/19504086/48625122-f0519c00-e9b6-11e8-87cd-a58d11f43316.png)
current 48.2%

**Comment by ameeramer** [comment]
![image](https://user-images.githubusercontent.com/19497043/48627908-84733180-e9be-11e8-9539-7774a6a28ad4.png)

**Comment by yuvalron** [comment]
![image](https://user-images.githubusercontent.com/19504086/48681529-9a921500-ebab-11e8-8a5b-719f7f6fec5b.png)

**Comment by ameeramer** [comment]
![image](https://user-images.githubusercontent.com/19497043/48721870-6b22ed00-ec2b-11e8-9e57-ed578ad70375.png)

**Comment by menhel** [comment]
Note: the badge in the readme is showing only 55%. This is due to the way Codecov's formula, which treat partials as 0% coverage instead of their actual percentage. This is not the case in Eclipse, and as we were instructed to check ourselves with Eclipse, this issue is still closed.

See snapshot from Codecov's website:
![image](https://user-images.githubusercontent.com/28152692/48781763-5acf4880-ece5-11e8-9b7b-e52ee22ae220.png)
