### ISSUE TITLE
move function read() from class FileUtils to class file

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#55]

**Comment by yuvalron** [comment]
1hr

**Comment by yuvalron** [comment]
0.5 hr

**Comment by yossigil** [comment]
please use comments on the commit so we know which issue you worked on, and which issue was closed by each commit

**Comment by yossigil** [comment]
@yuvalron , please create an issue with checklist to all team members so that they understand what needs to be done

**Comment by yuvalron** [comment]
no problem.
7d8a50f5824e5f2eb6133336cb6752f920184d83
