### ISSUE TITLE
move function readFromFile from class FileUtils to class file

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#57]

**Comment by ron4548** [comment]
Estimated time: 1/2 hour

**Comment by ron4548** [comment]
@yossigil No such method "readFromFile" in class FileUtils. Did you mean "writeToFile" method?

**Comment by ameeramer** [comment]
@ron4548 You won't find the method "readFromFile", issue #58 was to rename the function to "read".

**Comment by ron4548** [comment]
Looks like this and #55 are redundant once #58 was solved. So this should be marked as duplicate and closed.
@ameeramer @yuvalron Do you agree?

**Comment by ameeramer** [comment]
@ron4548 yes.

**Comment by menhel** [comment]
Closed as duplicate for #55 + #58, as @ron4548 stated
