### ISSUE TITLE
rename function readFromFile to read

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#58]

**Comment by ameeramer** [comment]
Estimated time to complete: 4-5 minutes.

**Comment by yossigil** [comment]
please provide a link to the commit that closed this issue

**Comment by ameeramer** [comment]
36dd19c40b0a372d0d9d36a0feb7c45ce607b0b1

**Comment by yossigil** [comment]
your commit message should be something like 'fixes #xxx'; if you do not understand this, raise this in telegram

**Comment by ameeramer** [comment]
I'll make sure to compose the right message for the next commits. is there anyway to change the current commit message? It seems as though the hash of the commit is computed dependent on the message, so it cannot be changed.

**Comment by yossigil** [comment]
NO. THERE IS NONE
