### ISSUE TITLE
make sure there are no warnings on code

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#63]

**Comment by dormaayan** [comment]
Please assign a team member to this issue ASAP

**Comment by menhel** [comment]
Estimated: 3 hours

**Comment by ameeramer** [comment]
Eliminated the warning "method has a constructor name" by changing it's name.

**Comment by menhel** [comment]
Done. All tests pass. No warnings.
![image](https://user-images.githubusercontent.com/28152692/48284746-01575600-e469-11e8-9db4-0349bfbc34d9.png)

Took 4 hours
