### ISSUE TITLE
Set up running environment - Guy Menhel

### ISSUE THREAD

**Issue by menhel** [TechnionYP5779/team4#64]
Definition Of Done (DOD):
Comment with a screenshot of your eclipse with a running project of Spartan

**Comment by yossigil** [comment]
a screen shot please!

**Comment by menhel** [comment]
Tests pass:
![image](https://user-images.githubusercontent.com/28152692/48237232-63af4880-e3ce-11e8-9d84-59bbeeb0b45b.png)

Eclipse configured as instructed:
![image](https://user-images.githubusercontent.com/28152692/48237177-2a76d880-e3ce-11e8-8923-500d29d88338.png)
