### ISSUE TITLE
Set up running enviroment - Ron Marcovich

### ISSUE THREAD

**Issue by ron4548** [TechnionYP5779/team4#66]
Definition Of Done (DOD):
Comment with a screenshot of your eclipse with a running project of Spartan

**Comment by ron4548** [comment]
<img width="544" alt="screen shot 2018-11-07 at 17 03 44" src="https://user-images.githubusercontent.com/4895877/48139443-2f913600-e2af-11e8-8618-9c78d785bc97.png">
Done. All tests pass

**Comment by yossigil** [comment]
nice to have also a photo of the clean warnings page...

**Comment by ron4548** [comment]
@yossigil Actually there are many warnings that exist in the code. Configured Eclipse as you instructed us on Telegram. What could be the reason for all the warnings?
<img width="694" alt="screen shot 2018-11-08 at 13 19 03" src="https://user-images.githubusercontent.com/4895877/48195654-e7c6e900-e358-11e8-9732-1b3d0954d2a3.png">

**Comment by yossigil** [comment]
someone broke the no warnings property; please fix it

**Comment by ron4548** [comment]
@yossigil Warnings will be handled as part of #63

**Comment by menhel** [comment]
@ron4548, the project now has no errors (#63). Make sure you pull the latest code from master, run it, and post a screenshot here.

**Comment by ron4548** [comment]
All tests pass. No warnings. Thanks @menhel 
![image](https://user-images.githubusercontent.com/4895877/48299868-fa1d6000-e4db-11e8-9a07-1e4385075f62.png)
