### ISSUE TITLE
Set up running enviroment - Max Calderon

### ISSUE THREAD

**Issue by maxcalderon1997** [TechnionYP5779/team4#69]
Definition Of Done (DOD):
Comment with a screenshot of your eclipse with a running project of Spartan

**Comment by maxcalderon1997** [comment]
Definition Of Done (DOD):
Comment with a screenshot of your eclipse with a running project of Spartan

**Comment by menhel** [comment]
@maxcalderon1997, the project now has no errors (#63). Make sure you pull the latest code from master, run it, and post a screenshot here.

**Comment by maxcalderon1997** [comment]
![image](https://user-images.githubusercontent.com/19844997/48299615-2931d280-e4d8-11e8-84d4-e8ba02822b95.png)
