### ISSUE TITLE
Refactor use of assertions

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team4#72]
All code in the project must use the azzert library in the project.

**Comment by yossigil** [comment]
what's up?

**Comment by menhel** [comment]
It is done, but the use of azzerts causes warnings, which we are working on fixing.
Will update soon.

**Comment by menhel** [comment]
Done. The warnings will be dealt with as part of this issue #63

**Comment by yossigil** [comment]
still `  @Test public void testToString() {
    Assert.assertEquals("<Hello,1>", Pair.newPair("Hello", Integer.valueOf(1)) + "");
  }`

**Comment by menhel** [comment]
Duplicate for #106 . Closing.
