### ISSUE TITLE
Define class range using tdd

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team4#73]
class range represents a range of integers, which could be infinite.

- [x] erase everhing in the class, and commit your erases.
use tdd to develop the class, as follows:
do at least one comit for each checkbox.

- [x] rang.from(2) create the infinite range 2.... 
- [x] range.from(2).from() returns the  starting point of the range
 - [x] range.from(2).to(6) returns the range 2,3,4,5
 - [x] range.to(2) returns the infinite range ..., -3, -2,-1,0,1
- [x] range.to(2).from() should return a null pointer
- [x] range.to(2).from(-5) is the range -5, -4, ...,0,1
- [x] range.numbers return an iterator over all integers in the range. 
- [x] range.to(10).interset(range.from(3)) crate the intersection range
- [x] range.from(x).to(y).includes(z) specifiy by yourself.

**Comment by Rany615** [comment]
how do we make it so that the same function can operate both on objects and as a static function?
range.from(2) create the infinite range 2....
range.to(2).from(-5) is the range -5, -4, ...,0,1

**Comment by yossigil** [comment]
distinct types

**Comment by Rany615** [comment]
same name?

**Comment by ameeramer** [comment]
@Rany615 please close the issue when completed. you can write "fixed #[isuue_no]" in the commit message, so the issue closes automatically.

**Comment by yossigil** [comment]
@Rany615 ???

**Comment by yossigil** [comment]
@Rany615 : THIS IS NOT AN ISSUE YOU WORKED ON
