### ISSUE TITLE
use tdd to develop a fluent api that represents an arithemtical progression over BigInteger

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team4#74]
See #73  on how to define the fluent API.
Add checkboxes as necessary, note that default first value is zero, default step should e zero, and default count is infinity

**Comment by yuvalron** [comment]
**Fluent API definition of BigIntegerRange class** 
Description: a range of BigIntegers, which could be infinite.
- [ ] default first value is 0.
- [ ] default step is 0.
- [ ] default count is infinity.
- [ ] rang.from(2) create the infinite range: 2, 3, .... 
- [ ] range.from(2).from() returns the starting point of the range.
- [ ] range.from(2).to(6) returns the range 2, 3, 4, 5.
- [ ] range.to(2) returns the infinite range ..., -3, -2, -1, 0, 1.
- [ ] range.to(2).from() should return a null pointer.
- [ ] range.to(2).from(-5) is the range -5, -4, ..., 0, 1.
- [ ] range.numbers return an iterator over all integers in the range. 
- [ ] range.to(10).interset(range.from(3)) crate the intersection range.
- [ ] range.from(x).to(y).includes(z) specifiy by yourself.

**Comment by dormaayan** [comment]
Yes

**Comment by yuvalron** [comment]
@dormaayan 
Is there a chance you meant the default step to be ONE and not ZERO?
