### ISSUE TITLE
use tdd to define a class that defines a list of pairs of real numbers

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team4#76]
this list could be used e.g., for representing a set of data points to draw in an xy graph, 
e.g., x is time and y is weight. the series is the list of data points.

- [x]  function recod(x,y)
- [x] iteration over pairs sorted by
- [x] statistics, such as count of data points.
- [x] implement linear regression https://en.wikipedia.org/wiki/Simple_linear_regression

**Comment by dormaayan** [comment]
@ameeramer It should define a record of x and y.

**Comment by yossigil** [comment]
THIS IS BUGGY

@Override public boolean equals(Object obj) {
    if (obj.hashCode() == this.hashCode() && obj == this)
        return true;	     


PLEASE FIX THIS

**Comment by yossigil** [comment]
no tests for the fix
