### ISSUE TITLE
Define class range using tdd

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team4#79]
class range represents a range of integers, which could be infinite.

- [ ] erase everhing in the class, and commit your erases.
use tdd to develop the class, as follows:
do at least one comit for each checkbox.

- [ ] rang.from(2) create the infinite range 2.... 
- [ ] range.from(2).from() returns the  starting point of the range
 - [ ] range.from(2).to(6) returns the range 2,3,4,5
 - [ ] range.to(2) returns the infinite range ..., -3, -2,-1,0,1
- [ ] range.to(2).from() should return a null pointer
- [ ] range.to(2).from(-5) is the range -5, -4, ...,0,1
- [ ] range.numbers return an iterator over all integers in the range. 
- [ ] range.to(10).interset(range.from(3)) crate the intersection range
- [ ] range.from(x).to(y).includes(z) specifiy by yourself.

**Comment by yuvalron** [comment]
duplicate. #73
