### ISSUE TITLE
use tdd to define a class that defines a list of pairs of real numbers

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team4#82]
this list could be used e.g., for representing a set of data points to draw in an xy graph, 
e.g., x is time and y is weight. the series is the list of data points.

- [ ]  function recod(x,y)
- [ ] iteration over pairs sorted by
- [ ] statistics, such as count of data points.
- [ ] implement linear regression https://en.wikipedia.org/wiki/Simple_linear_regression

**Comment by yuvalron** [comment]
duplicate. #76
