### ISSUE TITLE
move all inner TEST classes to the test hierarchy

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#88]

**Comment by menhel** [comment]
Remaining test to move:
- [ ] il.org.spartan - Utils.java
- [ ] fluent.ly - as.java
- [ ] fluent.ly - prune.java
- [ ] fluent.ly - seperate.java

**Comment by yossigil** [comment]
if you do not have a test source hierarchy, maven will not work, and you will not be able to maintain coverage.
You must have a source hierachy of tests.

Please read about this, and do not close this issue without @dormaayan approval

**Comment by ron4548** [comment]
![image](https://user-images.githubusercontent.com/4895877/48464782-62748600-e7e9-11e8-8b79-b095299a410f.png)
@dormaayan This is the test hierarchy we created. If this is not what you mean please let us know what is expected

**Comment by ameeramer** [comment]
![image](https://user-images.githubusercontent.com/19497043/48472284-97d79e80-e7fe-11e8-8654-6ed38a52f779.png)
