### ISSUE TITLE
Use TDD to develop a function iterables.alternate that takes two iterables, and returns an iterable that returns elements in these in alternating order, until the shortest

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#89]
_From @yossigil on November 8, 2018 10:18_

Use TDD to develop a function iterables.alternate that takes two iterables over elements of the same kind, and returns an iterable that returns elements in these in alternating order, until the shortest one is exhausted, and then continues with the other.

use TDD to design and implement specification for the case that one or both arguments are null.
be sure to break tests before you write any line of code.

_Copied from original issue: TechnionYP5779/team6#60_

**Comment by ron4548** [comment]
@yossigil What is the expected behaviour in case one or both of the iterables is null? Should we throw an exception?
