### ISSUE TITLE
Make sure all closed issues have an assignee

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#90]
_From @yossigil on November 8, 2018 10:48_

each one of you will need to make a report on what he did for the sprint, this report should include all non duplicate issues that he closed.

For this reason, we need to make sure that all duplicates are marked duplicate.

_Copied from original issue: TechnionYP5779/team6#61_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team1#57

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team2#53

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team3#70

**Comment by yuvalron** [comment]
Every closed issue has now an assignee.
