### ISSUE TITLE
use TDD to define class angle

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#91]
_From @yossigil on November 8, 2018 11:1_

that represents an angle on the plane; angles can be added, negated and substracted
here are some hints.

- [x] angle.degrees(20) creates an angle of 20 degrees
- [x] angle.radians(1) creates an angle of 1 radian
- [x] angle.pi is an angle of pi radians
- [x] angle.halfPi is an engle of half Pi radians
- [x] angle.halfPi.add(angle.degrees(20)) is an engle of half Pi radians + 20 radians
- [x] angle.halfPi.add((20)) is an engle of half Pi radians + 20 degrees
- [x] angle.pi.degrees() is 180
- [x] angle.of(20).degrees() is 180
- [x] angle.pi.radians() is PI/2

be sure to create code that try to cheat the tests, e.g. 
`class angle { static angle degrees(double x) { return new angle(20); }`

_Copied from original issue: TechnionYP5779/team6#62_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#96

**Comment by yossigil** [comment]
public static angle radians(double __) {
    forget.it(__);
    return new angle(1*rad2deg);
  }


this is not correct code.

**Comment by menhel** [comment]
In order to write code that tries to cheat the test, like you asked, the function argument remains unused.
To overcome this, I used the forget class. Another option was to suppress the warning. 
Which of those two method is more preferable? Is there another way I didn't think of?

**Comment by menhel** [comment]
I decided to suppress the warnings.
Closed the issue. Let me know if you want me to do anything else.
