### ISSUE TITLE
make sure all issues, including closed ones, have a milestone

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#93]
_From @yossigil on November 8, 2018 16:36_

to do so, apply searches in the issues tab of github

_Copied from original issue: TechnionYP5779/team1#60_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team2#55

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team3#72

**Comment by yuvalron** [comment]
All issues (including closed ones) have a milestone set to "Sprint 0"
