### ISSUE TITLE
Please use commits not pull requests

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#95]

**Comment by menhel** [comment]
@yossigil 
We have decided to adapt the GitFlow Methodology in this yearly project. I have published a Wiki page explaning all about it [here](https://github.com/TechnionYP5779/team4/wiki/GitFlow:-The-way-we-develop-features-and-close-issues).

 Although it is pretty robust for this demo project (the current issues), we felt that getting used to working in this organized manner will be beneficial for the future, actual project. Also, we wanted to make sure no team member overrides any other team member's work, so sticking to GitFlow will surely achieve this goal.

If you believe the flow described in the Wiki page linked above is not the way to go now, please let us know exactly how to handle out work, and I will make sure to update it in the Wiki for future work.

**Comment by yossigil** [comment]
GOOD IDEAS.

BUT,... YOU ARE NOT ALLOWED AT THIS STAGE TO USE GITFLOW. YOU HAVE TO FINISH ALL ISSUES ASAP, AND THERE ARE MANY OTHER PROBLEMS WITH YOUR TEAM. PLEASE DO NOT ADD ANY MORE
