### ISSUE TITLE
warnings etc

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#97]
Description	Resource	Path	Location	Type
Null type safety (type annotations): The expression of type 'T[]' needs unchecked conversion to conform to '@NotNull T []'	not.java	/fluent.ly/src/main/java/fluent/ly	line 5	Java Problem
Null type safety (type annotations): The expression of type 'T[]' needs unchecked conversion to conform to '@NotNull T []'	is.java	/fluent.ly/src/main/java/fluent/ly	line 38	Java Problem
Null type safety (type annotations): The expression of type 'T[]' needs unchecked conversion to conform to '@NotNull T []'	is.java	/fluent.ly/src/main/java/fluent/ly	line 48	Java Problem
Redundant null check: The variable ¢ cannot be null at this location	is.java	/fluent.ly/src/main/java/fluent/ly	line 19	Java Problem
The import java.util.stream is never used	is.java	/fluent.ly/src/main/java/fluent/ly	line 5	Java Problem
The import java.nio.charset is never used	FileUtils.java	/fluent.ly/src/main/java/il/org/spartan/utils	line 4	Java Problem
The import java.nio.file is never used	FileUtils.java	/fluent.ly/src/main/java/il/org/spartan/utils	line 5	Java Problem
Null type safety (type annotations): The expression of type 'Boolean' needs unchecked conversion to conform to '@NotNull Boolean'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 13	Java Problem
Null type safety (type annotations): The expression of type 'Boolean' needs unchecked conversion to conform to '@NotNull Boolean'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 14	Java Problem
Null type safety (type annotations): The expression of type 'Byte' needs unchecked conversion to conform to '@NotNull Byte'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 56	Java Problem
Null type safety (type annotations): The expression of type 'Character' needs unchecked conversion to conform to '@NotNull Character'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 43	Java Problem
Null type safety (type annotations): The expression of type 'Double' needs unchecked conversion to conform to '@NotNull Double'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 37	Java Problem
Null type safety (type annotations): The expression of type 'Double' needs unchecked conversion to conform to '@NotNull Double'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 38	Java Problem
Null type safety (type annotations): The expression of type 'Float' needs unchecked conversion to conform to '@NotNull Float'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 31	Java Problem
Null type safety (type annotations): The expression of type 'Integer' needs unchecked conversion to conform to '@NotNull Integer'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 19	Java Problem
Null type safety (type annotations): The expression of type 'Integer' needs unchecked conversion to conform to '@NotNull Integer'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 20	Java Problem
Null type safety (type annotations): The expression of type 'List<@NotNull Integer>' needs unchecked conversion to conform to '@NotNull List<Integer>'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 86	Java Problem
Null type safety (type annotations): The expression of type 'List<@NotNull Short>' needs unchecked conversion to conform to '@NotNull Collection<Short>', corresponding supertype is 'Collection<@NotNull Short>'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 135	Java Problem
Null type safety (type annotations): The expression of type 'Short' needs unchecked conversion to conform to '@NotNull Short'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 49	Java Problem
The static method assertArrayEquals(boolean[], boolean[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 65	Java Problem
The static method assertArrayEquals(boolean[], boolean[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 66	Java Problem
The static method assertArrayEquals(byte[], byte[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 155	Java Problem
The static method assertArrayEquals(byte[], byte[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 156	Java Problem
The static method assertArrayEquals(char[], char[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 125	Java Problem
The static method assertArrayEquals(char[], char[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 126	Java Problem
The static method assertArrayEquals(double[], double[], double) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 115	Java Problem
The static method assertArrayEquals(double[], double[], double) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 116	Java Problem
The static method assertArrayEquals(float[], float[], float) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 105	Java Problem
The static method assertArrayEquals(float[], float[], float) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 106	Java Problem
The static method assertArrayEquals(int[], int[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 76	Java Problem
The static method assertArrayEquals(int[], int[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 77	Java Problem
The static method assertArrayEquals(int[], int[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 86	Java Problem
The static method assertArrayEquals(long[], long[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 95	Java Problem
The static method assertArrayEquals(long[], long[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 96	Java Problem
The static method assertArrayEquals(short[], short[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 135	Java Problem
The static method assertArrayEquals(short[], short[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 136	Java Problem
The static method assertArrayEquals(short[], short[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 145	Java Problem
The static method assertArrayEquals(short[], short[]) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 146	Java Problem
The static method assertEquals(double, double, double) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 37	Java Problem
The static method assertEquals(double, double, double) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 38	Java Problem
The static method assertEquals(float, float, float) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 31	Java Problem
The static method assertEquals(float, float, float) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 32	Java Problem
The static method assertEquals(long, long) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 25	Java Problem
The static method assertEquals(long, long) from the type Assert should be accessed directly 	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 26	Java Problem
The import java.util.function is never used	Bool.java	/fluent.ly/src/main/java/il/org/spartan/utils	line 7	Java Problem
The import org.mockito.Mockito is never used	Bool.java	/fluent.ly/src/main/java/il/org/spartan/utils	line 3	Java Problem
Tip: Inline local o into subsequent statement	nil.java	/fluent.ly/src/main/java/fluent/ly	line 51	Inlining
Tip: Remove redundant [public] modifier	nil.java	/fluent.ly/src/main/java/fluent/ly	line 39	SyntacticBaggage
Tip: Remove redundant [static] modifier	nil.java	/fluent.ly/src/main/java/fluent/ly	line 39	SyntacticBaggage
Tip: Sort annotations of singleton method read ([@SuppressWarnings("null"), @NotNull]->[@NotNull, @SuppressWarnings("null")])	file.java	/fluent.ly/src/main/java/il/org/spartan/utils	line 51	Idiomatic
Tip: Remove redundant [public] modifier	count.java	/fluent.ly/src/main/java/fluent/ly	line 14	SyntacticBaggage
Tip: Remove redundant [static] modifier	count.java	/fluent.ly/src/main/java/fluent/ly	line 14	SyntacticBaggage
Tip: Rewrite 'azzert.assertTrue(count.of(Arrays.asList("Hello","World!","How","Are","You")) == 5)' as assert command	count.java	/fluent.ly/src/main/java/fluent/ly	line 16	Idiomatic
Tip: Rewrite 'azzert.assertTrue(count.of(new ArrayList<>()) == 0)' as assert command	count.java	/fluent.ly/src/main/java/fluent/ly	line 20	Idiomatic
Tip: Inline local mock into subsequent statement	anonymous.java	/fluent.ly/src/main/java/fluent/ly	line 36	Inlining
Tip: Inline local mock into subsequent statement	anonymous.java	/fluent.ly/src/main/java/fluent/ly	line 47	Inlining
Tip: Inline local mock into subsequent statement	anonymous.java	/fluent.ly/src/main/java/fluent/ly	line 58	Inlining
Tip: Inline local mock into subsequent statement	anonymous.java	/fluent.ly/src/main/java/fluent/ly	line 69	Inlining
Tip: Inline local mock into subsequent statement	anonymous.java	/fluent.ly/src/main/java/fluent/ly	line 80	Inlining
Tip: Remove redundant [public] modifier	anonymous.java	/fluent.ly/src/main/java/fluent/ly	line 34	SyntacticBaggage
Tip: Remove redundant [static] modifier	anonymous.java	/fluent.ly/src/main/java/fluent/ly	line 34	SyntacticBaggage
Tip: Rewrite 'azzert.that(ly(mock),is(true))' as assert command	anonymous.java	/fluent.ly/src/main/java/fluent/ly	line 43	Idiomatic
Tip: Inline local f into subsequent statement	Truth.java	/fluent.ly/src/main/java/il/org/spartan/utils	line 71	Inlining
Tip: Inline variable t into next statement	Truth.java	/fluent.ly/src/main/java/il/org/spartan/utils	line 69	Inlining
Tip: Inline local i into subsequent statement	Int.java	/fluent.ly/src/main/java/il/org/spartan/utils	line 71	Inlining
Tip: Convert post-increment of i to pre-increment	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 62	Idiomatic
Tip: Convert post-increment of i to pre-increment	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 73	Idiomatic
Tip: Convert post-increment of i to pre-increment	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 83	Idiomatic
Tip: Convert post-increment of i to pre-increment	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 92	Idiomatic
Tip: Convert post-increment of i to pre-increment	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 102	Idiomatic
Tip: Convert post-increment of i to pre-increment	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 112	Idiomatic
Tip: Convert post-increment of i to pre-increment	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 122	Idiomatic
Tip: Convert post-increment of i to pre-increment	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 132	Idiomatic
Tip: Convert post-increment of i to pre-increment	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 142	Idiomatic
Tip: Convert post-increment of i to pre-increment	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 152	Idiomatic
Tip: Remove redundant curly braces	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 62	SyntacticBaggage
Tip: Remove redundant curly braces	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 73	SyntacticBaggage
Tip: Remove redundant curly braces	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 83	SyntacticBaggage
Tip: Remove redundant curly braces	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 92	SyntacticBaggage
Tip: Remove redundant curly braces	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 102	SyntacticBaggage
Tip: Remove redundant curly braces	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 112	SyntacticBaggage
Tip: Remove redundant curly braces	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 122	SyntacticBaggage
Tip: Remove redundant curly braces	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 132	SyntacticBaggage
Tip: Remove redundant curly braces	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 142	SyntacticBaggage
Tip: Remove redundant curly braces	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 152	SyntacticBaggage
Tip: Rename iteration variable 'i' to '¢'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 62	Centification
Tip: Rename iteration variable 'i' to '¢'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 73	Centification
Tip: Rename iteration variable 'i' to '¢'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 83	Centification
Tip: Rename iteration variable 'i' to '¢'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 92	Centification
Tip: Rename iteration variable 'i' to '¢'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 102	Centification
Tip: Rename iteration variable 'i' to '¢'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 112	Centification
Tip: Rename iteration variable 'i' to '¢'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 122	Centification
Tip: Rename iteration variable 'i' to '¢'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 132	Centification
Tip: Rename iteration variable 'i' to '¢'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 142	Centification
Tip: Rename iteration variable 'i' to '¢'	BoxUnboxTest.java	/fluent.ly/src/main/java/fluent/ly	line 152	Centification

**Comment by menhel** [comment]
Duplicate for #63, which is in progress.
