### ISSUE TITLE
eliminate @SuppressWarnings("boxing")  placed for laziness

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#98]
you seem to be adding suppresswarning to eliminate warnings. this should be done only as last resort.
clearly not in this one. 

please go over code and make sure that @SuppressWarnings are not due to laziness

**Comment by yossigil** [comment]
You should have no warnings. And @menhel , please try to let others do some work

**Comment by ameeramer** [comment]
There are none.

**Comment by yossigil** [comment]
@ameeramer, next time please do not close issues that were reopened without a proper documentation. otherwise it becomes I say, you say.
