### ISSUE TITLE
clean run of tests

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#99]
_From @yossigil on November 8, 2018 19:25_

make sure that tests do not print anything to console. tests should be clean.
there are cases in which the not clean run indicates bad design. maybe you can find them

_Copied from original issue: TechnionYP5779/team6#65_

**Comment by menhel** [comment]
Clean console. See image below.
![image](https://user-images.githubusercontent.com/28152692/48267602-70b65100-e43b-11e8-9c3b-2eb85a943158.png)

**Comment by yossigil** [comment]
still not working! I cannot even get "run as junit test".

Your project is at mess

**Comment by ameeramer** [comment]
fixed in e9a02deb5fb220323f893c6f197ff97b9dea0a89

**Comment by yossigil** [comment]
your project does not compile still...

**Comment by menhel** [comment]
![image](https://user-images.githubusercontent.com/28152692/48464302-ceee8580-e7e7-11e8-97ba-a05de0b671a7.png)
---
![image](https://user-images.githubusercontent.com/28152692/48464523-7ff52000-e7e8-11e8-92b6-8c94fc31d294.png)
---

@yossigil For me it does. Can you please provide us with the compile errors you receive? make sure you pull, and refresh the eclipse environment before you try and run.

**Comment by ameeramer** [comment]
![image](https://user-images.githubusercontent.com/19497043/48472296-a32aca00-e7fe-11e8-9c71-5e4e43a4d911.png)
